name: AppImage generation with CMake on ubuntu-18.04

on:
  release:
    types: [created]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2

    - name: Update ubuntu
      run: |
        sudo apt update --yes && \
        sudo add-apt-repository ppa:team-xbmc/ppa && \
        sudo apt update --yes

    - name: Install ncurses
      run: sudo apt install libncurses5-dev libncursesw5-dev

    - name: Install curl
      run: sudo apt install libcurl4-openssl-dev

    - name: Install json parser
      run: sudo apt install nlohmann-json3-dev

    - name: Configure CMake
      # Configure CMake in a 'build' subdirectory. `CMAKE_BUILD_TYPE` is only required if you are using a single-configuration generator such as make.
      # See https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html?highlight=cmake_build_type
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      # Build your program with the given configuration
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
      
    - name: Download linuxdeploy
      working-directory: ${{github.workspace}}
      run: |
        wget https://github.com/linuxdeploy/linuxdeploy/releases/download/continuous/linuxdeploy-x86_64.AppImage && \
        chmod +x linuxdeploy-x86_64.AppImage

    - name: Generate AppImage
      working-directory: ${{github.workspace}}
      run: ./generate/generate-appimage.sh
      
    - name: Upload AppImage-Artifact
      uses: actions/upload-artifact@v2
      with:
        name: AppImage-Artifact
        path: quick_clone-*.AppImage
        retention-days: 5
