name: Release
on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+

jobs:
  appimage:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt update
        sudo add-apt-repository ppa:team-xbmc/ppa
        sudo apt update
        sudo apt install build-essential
        sudo apt install libncurses5-dev libncursesw5-dev
        sudo apt install libcurl4-openssl-dev
        sudo apt install nlohmann-json3-dev

    - name: Configure CMake
      working-directory: ${{github.workspace}}/build
      run: cmake ..

    - name: Build
      working-directory: ${{github.workspace}}
      run: make -C build/

    - name: Download linuxdeploy
      working-directory: ${{github.workspace}}
      run: |
        wget https://github.com/linuxdeploy/linuxdeploy/releases/download/continuous/linuxdeploy-x86_64.AppImage
        chmod +x linuxdeploy-x86_64.AppImage

    - name: Generate AppImage
      working-directory: ${{github.workspace}}
      run: ./generate/generate-appimage.sh

    - name: Upload AppImage-Artifact
      uses: actions/upload-artifact@v2
      with:
        name: appimage
        path: quick_clone-*.AppImage
        retention-days: 2
